using Vortice.Vulkan;
namespace Veldrid.Vk
{
    internal static partial class VkFormats
    {
        internal static VkFormat VdToVkPixelFormat(PixelFormat format, bool toDepthFormat = false)
        {
            return format switch
            {
                PixelFormat.R8UNorm => VkFormat.R8Unorm,
                PixelFormat.R8SNorm => VkFormat.R8Snorm,
                PixelFormat.R8UInt => VkFormat.R8Uint,
                PixelFormat.R8SInt => VkFormat.R8Sint,
                PixelFormat.R16UNorm => toDepthFormat ? VkFormat.D16Unorm : VkFormat.R16Unorm,
                PixelFormat.R16SNorm => VkFormat.R16Snorm,
                PixelFormat.R16UInt => VkFormat.R16Uint,
                PixelFormat.R16SInt => VkFormat.R16Sint,
                PixelFormat.R16Float => VkFormat.R16Sfloat,
                PixelFormat.R32UInt => VkFormat.R32Uint,
                PixelFormat.R32SInt => VkFormat.R32Sint,
                PixelFormat.R32Float => toDepthFormat ? VkFormat.D32Sfloat : VkFormat.R32Sfloat,
                PixelFormat.R8G8UNorm => VkFormat.R8G8Unorm,
                PixelFormat.R8G8SNorm => VkFormat.R8G8Snorm,
                PixelFormat.R8G8UInt => VkFormat.R8G8Uint,
                PixelFormat.R8G8SInt => VkFormat.R8G8Sint,
                PixelFormat.R16G16UNorm => VkFormat.R16G16Unorm,
                PixelFormat.R16G16SNorm => VkFormat.R16G16Snorm,
                PixelFormat.R16G16UInt => VkFormat.R16G16Uint,
                PixelFormat.R16G16SInt => VkFormat.R16G16Sint,
                PixelFormat.R16G16Float => VkFormat.R16G16B16A16Sfloat,
                PixelFormat.R32G32UInt => VkFormat.R32G32Uint,
                PixelFormat.R32G32SInt => VkFormat.R32G32Sint,
                PixelFormat.R32G32Float => VkFormat.R32G32B32A32Sfloat,
                PixelFormat.R8G8B8A8UNorm => VkFormat.R8G8B8A8Unorm,
                PixelFormat.R8G8B8A8UNormSRgb => VkFormat.R8G8B8A8Srgb,
                PixelFormat.B8G8R8A8UNorm => VkFormat.B8G8R8A8Unorm,
                PixelFormat.B8G8R8A8UNormSRgb => VkFormat.B8G8R8A8Srgb,
                PixelFormat.R8G8B8A8SNorm => VkFormat.R8G8B8A8Snorm,
                PixelFormat.R8G8B8A8UInt => VkFormat.R8G8B8A8Uint,
                PixelFormat.R8G8B8A8SInt => VkFormat.R8G8B8A8Sint,
                PixelFormat.R16G16B16A16UNorm => VkFormat.R16G16B16A16Unorm,
                PixelFormat.R16G16B16A16SNorm => VkFormat.R16G16B16A16Snorm,
                PixelFormat.R16G16B16A16UInt => VkFormat.R16G16B16A16Uint,
                PixelFormat.R16G16B16A16SInt => VkFormat.R16G16B16A16Sint,
                PixelFormat.R16G16B16A16Float => VkFormat.R16G16B16A16Sfloat,
                PixelFormat.R32G32B32A32UInt => VkFormat.R32G32B32A32Uint,
                PixelFormat.R32G32B32A32SInt => VkFormat.R32G32B32A32Sint,
                PixelFormat.R32G32B32A32Float => VkFormat.R32G32B32A32Sfloat,
                PixelFormat.Bc1RgbUNorm => VkFormat.Bc1RgbUnormBlock,
                PixelFormat.Bc1RgbUNormSRgb => VkFormat.Bc1RgbSrgbBlock,
                PixelFormat.Bc1RgbaUNorm => VkFormat.Bc1RgbaUnormBlock,
                PixelFormat.Bc1RgbaUNormSRgb => VkFormat.Bc1RgbaSrgbBlock,
                PixelFormat.Bc2UNorm => VkFormat.Bc2UnormBlock,
                PixelFormat.Bc2UNormSRgb => VkFormat.Bc2SrgbBlock,
                PixelFormat.Bc3UNorm => VkFormat.Bc3UnormBlock,
                PixelFormat.Bc3UNormSRgb => VkFormat.Bc3SrgbBlock,
                PixelFormat.Bc4UNorm => VkFormat.Bc4UnormBlock,
                PixelFormat.Bc4SNorm => VkFormat.Bc4SnormBlock,
                PixelFormat.Bc5UNorm => VkFormat.Bc5UnormBlock,
                PixelFormat.Bc5SNorm => VkFormat.Bc5SnormBlock,
                PixelFormat.Bc7UNorm => VkFormat.Bc7UnormBlock,
                PixelFormat.Bc7UNormSRgb => VkFormat.Bc7SrgbBlock,
                PixelFormat.Etc2R8G8B8UNorm => VkFormat.Etc2R8G8B8UnormBlock,
                PixelFormat.Etc2R8G8B8A1UNorm => VkFormat.Etc2R8G8B8A1UnormBlock,
                PixelFormat.Etc2R8G8B8A8UNorm => VkFormat.Etc2R8G8B8A8UnormBlock,
                PixelFormat.D32FloatS8UInt => VkFormat.D32SfloatS8Uint,
                PixelFormat.D24UNormS8UInt => VkFormat.D24UnormS8Uint,
                PixelFormat.R10G10B10A2UNorm => VkFormat.A2B10G10R10UnormPack32,
                PixelFormat.R10G10B10A2UInt => VkFormat.A2B10G10R10UintPack32,
                PixelFormat.R11G11B10Float => VkFormat.B10G11R11UfloatPack32,
                _ => throw new VeldridException($"Invalid {nameof(PixelFormat)}: {format}"),
            };
        }
    }
}
